Suggest `VanillaICE`
To fix following error from Travis:

Quitting from lines 51-61 (FindCNPs.Rmd) 
Error: processing vignette 'FindCNPs.Rmd' failed with diagnostics:
unable to find required package 'VanillaICE'
Execution halted