Don't evaluate `collapseBatch` section of vignette
Causes following error

Quitting from lines 249-262 (Implementation.Rmd) 
Error: processing vignette 'Implementation.Rmd' failed with diagnostics:
NA in probability vector
Execution halted